name: Continuous Delivery
on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  checks: write
  pull-requests: write

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Debug GitHub Context
        run: echo "${{ toJson(github) }}"

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            `**.py`
            `README.md`